export const NOTIFY = "NOTIFY";

export const FETCH_RISLIST_SUCCESS = "FETCH_RISLIST_SUCCESS";
export const FETCH_RISLIST_REQUEST = "FETCH_RISLIST_REQUEST";
export const FETCH_RISLIST_FAILURE = "FETCH_RISLIST_FAILURE";

export const RISLIST_ROW_SELECT = "RISLIST_ROW_SELECT";
export const RISLIST_ITEMS_ROW_SELECT = "RISLIST_ITEMS_ROW_SELECT";

export const FETCH_SELECTED_RIS_VALUES_REQUEST = "FETCH_SELECTED_RIS_VALUES_REQUEST";
export const FETCH_SELECTED_RIS_VALUES_SUCCESS = "FETCH_SELECTED_RIS_VALUES_SUCCESS";
export const FETCH_SELECTED_RIS_VALUES_FAILURE = "FETCH_SELECTED_RIS_VALUES_FAILURE";

export const SAVE_RIS_REQUEST = "SAVE_RIS_REQUEST";
export const SAVE_RIS_SUCCESS = "SAVE_RIS_SUCCESS";
export const SAVE_RIS_FAILURE = "SAVE_RIS_FAILURE";

export const UPDATE_RIS_REQUEST = "UPDATE_RIS_REQUEST";
export const UPDATE_RIS_SUCCESS = "UPDATE_RIS_SUCCESS";
export const UPDATE_RIS_FAILURE = "UPDATE_RIS_FAILURE";

export const DELETE_RIS_REQUEST = "DELETE_RIS_REQUEST";
export const DELETE_RIS_SUCCESS = "DELETE_RIS_SUCCESS";
export const DELETE_RIS_FAILURE = "DELETE_RIS_FAILURE";

export const SAVE_RIS_ITEM_REQUEST = "SAVE_RIS_ITEM_REQUEST";
export const SAVE_RIS_ITEM_SUCCESS = "SAVE_RIS_ITEM_SUCCESS";
export const SAVE_RIS_ITEM_FAILURE = "SAVE_RIS_ITEM_FAILURE";

export const UPDATE_RIS_ITEM_REQUEST = "UPDATE_RIS_ITEM_REQUEST";
export const UPDATE_RIS_ITEM_SUCCESS = "UPDATE_RIS_ITEM_SUCCESS";
export const UPDATE_RIS_ITEM_FAILURE = "UPDATE_RIS_ITEM_FAILURE";

export const DELETE_RIS_ITEM_REQUEST = "DELETE_RIS_ITEM_REQUEST";
export const DELETE_RIS_ITEM_SUCCESS = "DELETE_RIS_ITEM_SUCCESS";
export const DELETE_RIS_ITEM_FAILURE = "DELETE_RIS_ITEM_FAILURE";
